"""Generate shared vector exports; --check fails when packaged assets drift."""
import argparse
from pathlib import Path
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parents[1]
drawable = root / 'android/app/src/main/res/drawable'
namespace = '{http://schemas.android.com/apk/res/android}'
vector = ET.parse(drawable / 'ic_onework_mark.xml').getroot()
layers = [{key: p.attrib[namespace + key] for key in ('name', 'fillColor', 'pathData')}
          for p in vector.findall('path')]
assert [p['name'] for p in layers] == ['wing', 'head', 'beak', 'perch']
assert vector.attrib[namespace + 'viewportWidth'] == '64'
assert vector.attrib[namespace + 'viewportHeight'] == '64'
foreground = ['<vector xmlns:android="http://schemas.android.com/apk/res/android"',
              '    android:width="108dp" android:height="108dp"',
              '    android:viewportWidth="108" android:viewportHeight="108">',
              '    <!-- Generated by agent_views/macos/sync_brand.py; edit ic_onework_mark.xml. -->',
              '    <group android:translateX="22" android:translateY="22">']
svg = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">',
       '  <title>OneWork Perch</title>']
for layer in layers:
    name, data = layer['name'], layer['pathData']
    color = layer['fillColor'] if name == 'beak' else '#FFFFFF'
    foreground.append(f'        <path android:name="{name}" android:fillColor="{color}" android:pathData="{data}" />')
    svg.append(f'  <path id="{name}" fill="{layer["fillColor"]}" d="{data}" />')
foreground += ['    </group>', '</vector>']
svg.append('</svg>')
outputs = {drawable / 'ic_onework_foreground.xml': '\n'.join(foreground) + '\n',
           root / 'brand/onework-perch.svg': '\n'.join(svg) + '\n'}
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
for path, content in outputs.items():
    if args.check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f'Brand asset out of sync: {path}')
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
print('Perch brand assets verified' if args.check else 'Perch brand assets generated')
